version: '3.8'
services:
  db:
    image: postgres:latest
    restart: no
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"

volumes:
  postgres-data: